version: 2.1
jobs:
  build:
    working_directory: ~/ruby-salesApp
    parallelism: 1
    shell: /bin/bash --login

    environment:
      RAILS_ENV: test
      CIRCLE_ARTIFACTS: /tmp/circleci-artifacts
      CIRCLE_TEST_REPORTS: /tmp/circleci-test-results
      BUNDLE_PATH: vendor/bundle

    docker:
      - image: cimg/ruby:2.7.5-node
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD

        environment:
          RAILS_ENV: test
          PGHOST: 127.0.0.1
          PGUSER: root

      - image: cimg/postgres:14.0
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD
        environment:
          PGPASSWORD:
          POSTGRES_USER: root
          POSTGRES_PASSWORD:

    steps:
      - checkout
      - restore_cache:
          keys:
            - gem-cache-{{ checksum "Gemfile.lock" }}
            - gem-cache-
      - restore_cache:
          keys:
            - coverage-cache-master-coverage

      - run: gem install bundler:2.3.4

      - run:
          name: Bundle Install
          command: bundle install
          no_output_timeout: 1000s

      - save_cache:
          key: gem-cache-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
            - ~/.bundle

  rubocop:
    executor: default
    steps:
      - attach_workspace:
          at: ~/
      - configure_bundler
      - run:
          name: Rubocop
          command: bundle exec rubocop

  workflows:
    version: 2
    integration:
      jobs:
        - build
        - rubocop:
            requuires:
              - build

      - run: sudo apt-get update
      - run: sudo apt-get install postgresql-client
      - run: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run: RAILS_ENV=test bundle exec rails db:create --trace
      - run: RAILS_ENV=test bundle exec rails db:schema:load --trace
      - run: bundle exec rails spec

