development:
  adapter: postgresql
  encoding: unicode
  database: sales_app_development
  pool: 5
  host: localhost
  username: postgres
  password: Osasenaga2002

test:
  adapter: postgresql
  encoding: unicode
  database: sales_app_test
  pool: 5
  username: postgres
  password: Osasenaga2002

staging:
  url: <%= ENV['DATABASE_URL'] %>

production:
  url: <%= ENV['DATABASE_URL'] %>
